---
- name: Create vault group
  ansible.builtin.group:
    name: "{{ vault_group }}"
    system: true

- name: Create vault user
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: true
    shell: /bin/false
    home: "{{ vault_dir }}"
    create_home: false

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0750"
  loop:
    - "{{ vault_dir }}"
    - "{{ vault_data_dir }}"
    - "{{ vault_config_dir }}"

- name: Download vault binary
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/tmp/vault_{{ vault_version }}.zip"
    mode: "0644"

- name: Unzip vault binary
  ansible.builtin.unarchive:
    src: "/tmp/vault_{{ vault_version }}.zip"
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"

- name: Set vault capabilities
  community.general.capabilities:
    path: /usr/local/bin/vault
    capability: cap_ipc_lock+ep
    state: present
