---
gitlab_runner_name: "{{ inventory_hostname }}"
gitlab_runner_executor: docker
gitlab_runner_docker_image: "alpine:latest"
gitlab_runner_tags: []
gitlab_runner_run_untagged: true
gitlab_runner_concurrent: 4
