---
gitlab_runner_gitlab_url: "https://gitlab.{{ base_domain }}"
gitlab_runner_version: "18.11.2-1"
gitlab_runner_tags:
  - linux
gitlab_runner_run_untagged: false
gitlab_runner_api_token: "{{ vault_gitlab_runner_api_token }}"