---
- name: Remove conflicting docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
    state: absent
    autoremove: true
  when: docker_remove_conflicting_packages

- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install docker apt sign key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "0644"

- name: Configure docker apt repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components: "{{ docker_repo_channel }}"
    architectures: "{{ docker_apt_arch_map[ansible_architecture] | default(ansible_architecture) }}"
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
    enabled: true
