---
vault_version: "1.19.3"
vault_dir: /opt/vault
vault_data_dir: /opt/vault/data
vault_config_dir: /etc/vault.d
vault_user: vault
vault_group: vault
vault_port: 8200
vault_cluster_port: 8201

vault_backup_script_path: /usr/local/bin/vault-backup-r2.sh
vault_backup_schedule: "*-*-* 04:00:00"
vault_backup_keep_days: 7
